flowchart LR
%% Actors (using circles)
    T((Teacher))
    S((Student))
    G((guest))

    subgraph "Scrum School Platform"
        direction TB
    %% Use stadium shapes [()] for Use Cases
        UC_Login([Login])
        UC_Register([Register])

        UC_CreateProject([Create Project])
        UC_ManageProject([Manage Project Status])
        UC_AssignStudent([Assign Students])

        UC_CreateSprint([Create Sprint])
        UC_ViewSprints([View Sprints])
        UC_SubmitStandup([Submit Daily Standup])
        UC_ViewStandups([View Standups])
        UC_SubmitRetro([Submit Retrospective])
        UC_ViewRetros([View Retrospectives])

        UC_CreateTask([Create Task])
        UC_ViewTasks([View Tasks])
        UC_UpdateTaskStatus([Update Task Status])
        UC_SubmitSolution([Submit Task Solution])
        UC_ReviewSolution([Review Solution & Feedback])

        UC_ReportIssue([Report Task Issue])
        UC_ReplyIssue([Reply to Issue])

        UC_AwardAchievement([Award Achievement])
        UC_ViewAchievements([View Achievements])
    end

%% Relationships - Teacher
    T --- UC_CreateProject
    T --- UC_ManageProject
    T --- UC_AssignStudent
    T --- UC_CreateSprint
    T --- UC_CreateTask
    T --- UC_ViewStandups
    T --- UC_ViewRetros
    T --- UC_ReviewSolution
    T --- UC_ReplyIssue
    T --- UC_AwardAchievement

%% Relationships - Student
    S --- UC_ViewSprints
    S --- UC_ViewTasks
    S --- UC_UpdateTaskStatus
    S --- UC_SubmitSolution
    S --- UC_SubmitStandup
    S --- UC_SubmitRetro
    S --- UC_ReportIssue
    S --- UC_ReplyIssue
    S --- UC_ViewAchievements

%% Relationships - Guest

    G --- UC_Register
    G --- UC_Login
